//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.19 at 07:28:15 PM IST 
//


package in.iserveu.com.devices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deviceDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deviceDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="POS" type="{http://com.iserveu.in/devices}POS"/>
 *         &lt;element name="micro-ATM" type="{http://com.iserveu.in/devices}micro-ATM"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deviceDetails", propOrder = {
    "pos",
    "microATM"
})
public class DeviceDetails {

    @XmlElement(name = "POS", required = true)
    protected POS pos;
    @XmlElement(name = "micro-ATM", required = true)
    protected MicroATM microATM;

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link POS }
     *     
     */
    public POS getPOS() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link POS }
     *     
     */
    public void setPOS(POS value) {
        this.pos = value;
    }

    /**
     * Gets the value of the microATM property.
     * 
     * @return
     *     possible object is
     *     {@link MicroATM }
     *     
     */
    public MicroATM getMicroATM() {
        return microATM;
    }

    /**
     * Sets the value of the microATM property.
     * 
     * @param value
     *     allowed object is
     *     {@link MicroATM }
     *     
     */
    public void setMicroATM(MicroATM value) {
        this.microATM = value;
    }

}
