//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.19 at 07:28:15 PM IST 
//


package in.iserveu.com.devices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="micro-ATM-device-detail" type="{http://com.iserveu.in/devices}micro-ATM"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "microATMDeviceDetail"
})
@XmlRootElement(name = "getATMDeviceResponse")
public class GetATMDeviceResponse {

    @XmlElement(name = "micro-ATM-device-detail", required = true)
    protected MicroATM microATMDeviceDetail;

    /**
     * Gets the value of the microATMDeviceDetail property.
     * 
     * @return
     *     possible object is
     *     {@link MicroATM }
     *     
     */
    public MicroATM getMicroATMDeviceDetail() {
        return microATMDeviceDetail;
    }

    /**
     * Sets the value of the microATMDeviceDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link MicroATM }
     *     
     */
    public void setMicroATMDeviceDetail(MicroATM value) {
        this.microATMDeviceDetail = value;
    }

}
