//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.19 at 07:28:15 PM IST 
//


package in.iserveu.com.devices;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the in.iserveu.com.devices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: in.iserveu.com.devices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDeviceRequest }
     * 
     */
    public GetDeviceRequest createGetDeviceRequest() {
        return new GetDeviceRequest();
    }

    /**
     * Create an instance of {@link GetPOSDeviceRequest }
     * 
     */
    public GetPOSDeviceRequest createGetPOSDeviceRequest() {
        return new GetPOSDeviceRequest();
    }

    /**
     * Create an instance of {@link GetATMDeviceRequest }
     * 
     */
    public GetATMDeviceRequest createGetATMDeviceRequest() {
        return new GetATMDeviceRequest();
    }

    /**
     * Create an instance of {@link GetATMDeviceListResponse }
     * 
     */
    public GetATMDeviceListResponse createGetATMDeviceListResponse() {
        return new GetATMDeviceListResponse();
    }

    /**
     * Create an instance of {@link MicroATM }
     * 
     */
    public MicroATM createMicroATM() {
        return new MicroATM();
    }

    /**
     * Create an instance of {@link GetATMDeviceListRequest }
     * 
     */
    public GetATMDeviceListRequest createGetATMDeviceListRequest() {
        return new GetATMDeviceListRequest();
    }

    /**
     * Create an instance of {@link GetPOSDeviceResponse }
     * 
     */
    public GetPOSDeviceResponse createGetPOSDeviceResponse() {
        return new GetPOSDeviceResponse();
    }

    /**
     * Create an instance of {@link POS }
     * 
     */
    public POS createPOS() {
        return new POS();
    }

    /**
     * Create an instance of {@link GetATMDeviceResponse }
     * 
     */
    public GetATMDeviceResponse createGetATMDeviceResponse() {
        return new GetATMDeviceResponse();
    }

    /**
     * Create an instance of {@link GetAllDeviceRequest }
     * 
     */
    public GetAllDeviceRequest createGetAllDeviceRequest() {
        return new GetAllDeviceRequest();
    }

    /**
     * Create an instance of {@link GetAllDeviceResponse }
     * 
     */
    public GetAllDeviceResponse createGetAllDeviceResponse() {
        return new GetAllDeviceResponse();
    }

    /**
     * Create an instance of {@link DeviceDetails }
     * 
     */
    public DeviceDetails createDeviceDetails() {
        return new DeviceDetails();
    }

}
